package com.github.generator.usecases

object GeoData {
  val cities = Map(
    "AM" -> Seq("Yerevan", "Gyumri"),
    "BG" -> Seq("Sofia", "Plovdiv", "Varna"),
    "HR" -> Seq("Dubrovnik", "Split", "Zagreb"),
    "CZ" -> Seq("Brno", "Prague", "Tabor"),
    "FR" -> Seq("Bordeaux",
                "Cannes",
                "Lille",
                "Lyon",
                "Marseille",
                "Nantes",
                "Paris",
                "Saint Tropez",
                "Toulon",
                "Toulouse"),
    "GE" -> Seq("Tbilisi", "Batumi", "Kutaisi"),
    "GR" -> Seq("Athens", "Rhodos", "Rethymnon", "Saloniki"),
    "HU" -> Seq("Budapest", "Szeged"),
    "IE" -> Seq("Dublin", "Newcastle", "Shannon"),
    "IT" -> Seq("Florence", "Milan", "Naples", "Palermo", "Olbia", "Pisa"),
    "MT" -> Seq("Gozo", "Malta", "Comino"),
    "PL" -> Seq("Poznan", "Warsaw", "Wroclaw"),
    "PT" -> Seq("Coimbra", "Faro", "Lisboa", "Santa Maria"),
    "RO" -> Seq("Bucharest", "Deva"),
    "RU" -> Seq("Spb",
                "Moscow",
                "Omsk",
                "Sochi",
                "Khabarovsk",
                "Murmansk",
                "Irkutsk",
                "Kazan",
                "Kursk",
                "Magadan",
                "Rostov"),
    "US" -> Seq("New York", "Washington", "San Francisco", "Las Vegas", "Maiami"),
    "GB" -> Seq("London", "Birmingham", "Bristol", "Nottingham", "Oxford", "Belfast", "Glasgow", "Cardiff"),
    "DE" -> Seq("Berlin", "Hamburg", "Munich", "Bonn", "Bremen", "Dortmund", "Dresden", "Frankfurt", "Hannover"),
    "AT" -> Seq("Vienna", "Salzburg", "Reutte", "Graz", "Innsbruck", "Klagenfurt"),
    "UA" -> Seq("Kiev", "Kharkiv", "Odesa", "Mykolaiv", "Poltava", "Dnipro", "Lviv", "Cherkasy"),
    "BY" -> Seq("Minsk", "Vitebsk", "Brest", "Hrodna"),
    "CH" -> Seq("Zurich", "Geneva", "Zug", "Montreux", "Thun", "Lausanne"),
    "IL" -> Seq("Tel-Aviv", "Jerusalem", "Haifa", "Eilat"),
    "EE" -> Seq("Tallinn", "Narva", "Tartu"),
    "LV" -> Seq("Riga", "Daugavpils", "Yurmala"),
    "LT" -> Seq("Vilnius", "Kaunas", "Klaipeda"),
    "FI" -> Seq("Helsinki", "Oulu", "Imatra", "Tampere"),
    "SE" -> Seq("Malmo", "Stockholm", "Uppsala"),
    "NO" -> Seq("Bergen", "Oslo", "Kirkenes", "Tromso"),
    "DK" -> Seq("Copenhagen", "Karup"),
    "IS" -> Seq("Reykjavik"),
    "NL" -> Seq("Amsterdam", "The Hague", "Eindhoven", "Maastricht", "Rotterdam", "Utrecht"),
    "BE" -> Seq("Antwerp", "Brugge", "Brussels", "Liege"),
    "ES" -> Seq("Alicante",
                "Las Palmas",
                "Madrid",
                "Malaga",
                "Palma De Mallorca",
                "Sevilla",
                "Tenerife",
                "Toledo",
                "Valencia",
                "Zaragoza"),
    "TR" -> Seq("Ankara", "Istanbul", "Izmir", "Marmaris"),
    "US" -> Seq("New York", "Washington", "San Francisco", "Las Vegas", "Maiami"),
    "CA" -> Seq("Quebec", "Montreal", "Winnipeg"),
    "IN" -> Seq("Agra", "Bangalore", "Mumbai", "Calcutta", "Delhi"),
    "ID" -> Seq("Jakarta", "Padang"),
    "JP" -> Seq("Hiroshima", "Nagoya", "Okinawa", "Osaka", "Sapporo", "Tokyo", "Yokohama"),
    "KZ" -> Seq("Aralsk", "Almaty", "Ekibastuz", "Pavlodar", "Zhambyl"),
    "KR" -> Seq("Cheongju", "Seoul", "Yeosu"),
    "MY" -> Seq("Kuala Lumpur", "Kuching", "Long Akah", "Sepang"),
    "MN" -> Seq("Ulan Bator"),
    "PK" -> Seq("Karachi", "Lahore", "Sargodha"),
    "PH" -> Seq("Busuanga", "Roxas"),
    "SA" -> Seq("Al Kharj", "Dammam", "Jeddah", "Riyadh"),
    "TW" -> Seq("Taipei", "Taitung", "Xiaoliuqiu"),
    "TH" -> Seq("Bangkok", "Phuket", "Lop Buri"),
    "AE" -> Seq("Abu Dhabi", "Dubai", "Sharjah"),
    "UZ" -> Seq("Bukhara", "Tashkent", "Samarkand"),
    "VN" -> Seq("Hanoi", "Nha Trang")
  )
}
